import type { Metadata } from "next";
import "./globals.css";
import poppins from '@/constants/poppins'

export const metadata: Metadata = {
  title: "Tahsin App",
  description: "Generated by tahsin app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <body
        className={` ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
