import type { Metadata } from 'next';
import './globals.css';
import poppins from '@/constants/poppins';
import { Providers } from './providers';

export const metadata: Metadata = {
  title: 'Tahsin App',
  description: 'Generated by tahsin app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`light ${poppins.className}`}>
      <body className={` ${poppins.variable} antialiased overflow-y-hidden`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
